<a href="https://colab.research.google.com/github/Sugandh147/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

basic array creation

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
import numpy as np
a = [1,2,3,"hello"]
np.array(a)    # datatype u32 means all the datatype have been converted to unicode that is strings cause numpy accepts only similar datatypes

array(['1', '2', '3', 'hello'], dtype='<U21')

In [ ]:
import numpy as np
a = [1,2,3,4.6]
np.array(a)    # now everything is converted to float cause ek float value thi so everytging is converted to float (similar datatype)

array([1. , 2. , 3. , 4.6])

In [ ]:
l = [[1,2,3],[3,4,5],[6,7,8,]]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

array generation function

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,3)   # when u press shift and enter on a particular function it tells us what teh function does
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(1,5,5)   # lin space is called linear space and gives equal spaces between each element
arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr = np.linspace(1,5,10)   # lin space is called linear space and gives equal spaces between each element
arr                      # means 1 and 5 k beech mei 10 elements generate karega with equal spaces in between

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

random generation function

In [ ]:
np.random.rand(5)

array([0.13835855, 0.99688891, 0.00644439, 0.70027739, 0.10551773])

In [ ]:
np.random.randn(10)

array([ 1.98809672, -1.2638847 ,  0.38455117,  1.00410626,  2.07904856,
        0.72130942, -1.34795345,  0.54731068, -0.77492885,  0.63183719])

In [ ]:
import numpy as np
np.random.randint(6)

4

In [ ]:
np.random.randint(10,20,9)

array([10, 12, 10, 18, 17, 10, 18, 13, 11])

array attributes   (attributes are type of variable defined inside a class)

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

array methods


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(6)

In [ ]:
arr.sum()

np.int64(21)

In [ ]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [ ]:
np.sum(arr , axis = 1)

array([ 6, 15])

In [ ]:
arr.mean()

np.float64(3.5)

In [ ]:
arr.std()

np.float64(1.707825127659933)

In [ ]:
arr.argmax()

np.int64(5)

In [ ]:
arr.argmin()

np.int64(0)

reshaping and resizing


In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# INDEXING AND SLICING



In [ ]:
import numpy as np

numpy indexing and slicing of vector

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[2]  # printing using index

np.int64(13)

In [ ]:
arr [-1]

np.int64(20)

In [ ]:
arr[1:5]  # jis elemnt tak slice karna hai vha tak nhi likhna usme +1 karke likhna hai like i wanted to slice upt 15 which is at index 4 so mai vha tak nhi likhna instead 5 tak likhna

array([12, 13, 14, 15])

In [ ]:
arr[:6] # means 0 se lekar 5 index tak it will slice

array([11, 12, 13, 14, 15, 16])

In [ ]:
arr[3:] # means 4 se lekar last index tak slice hoga

array([14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::2] # 3 index se lekar end tak jayega 2 2 ke skip karke

array([14, 16, 18, 20])

In [ ]:
arr[3:9:1]

array([14, 15, 16, 17, 18, 19])

numpy indexing and slicing of matrix

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0,0]

np.int64(1)

In [ ]:
arr[5,4]

np.int64(30)

In [ ]:
arr[0:2,1:3]   # row wala part in this here it is we want row mwi se 0 and 1 row print and column mei we want 1 se lekar 2 tak print ho

array([[2, 3],
       [7, 8]])

In [ ]:
arr[3: ,2: ] # means row we wnat 3 se lekar end row tak and column we want 2 se lekar end tak

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [ ]:
arr[:,2] # means sari rows ka second column (so yeh ek vector hi ban chuka hai)

array([ 3,  8, 13, 18, 23, 28])

boolean indexing


In [2]:
import numpy as np
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
import numpy as np
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [6]:
arr = arr[bool_index]
arr    # mai apni array ke andar ool index ko bhej rhi hu so jha jha true hai vhi wale elements print hojayenge baaki false wale nhi honge

array([12, 14, 16, 18, 20])

In [ ]:
import numpy as np

# array operations

In [10]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1+a2     # size of both the arrays should be same for performing some operations

array([ 7,  9, 11, 13, 15])

In [15]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1-a2

array([-5, -5, -5, -5, -5])

In [16]:
arr2 = a1*a2
arr2

array([ 6, 14, 24, 36, 50])

In [17]:
arr3 = a1/a2
arr3

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
arr4 = a1 ** a2
arr4

array([      1,     128,    6561,  262144, 9765625])

broadcasting

In [20]:
l = [10,20,30,40]
arr = np.array(l)

In [21]:
arr + 10   # this is the basic case of broadcasting which means if aapke pass multiple elements hai and u want to add a single element into all elemets then u will use broadcasting

array([20, 30, 40, 50])

In [24]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
arr2 + 10  # u can broadcast in both arrays and ,atrices as well aside from vectors

array([16, 24, 34, 46, 60])