<a href="https://colab.research.google.com/github/Sugandh147/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

basic array creation

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
import numpy as np
a = [1,2,3,"hello"]
np.array(a)    # datatype u32 means all the datatype have been converted to unicode that is strings cause numpy accepts only similar datatypes

array(['1', '2', '3', 'hello'], dtype='<U21')

In [ ]:
import numpy as np
a = [1,2,3,4.6]
np.array(a)    # now everything is converted to float cause ek float value thi so everytging is converted to float (similar datatype)

array([1. , 2. , 3. , 4.6])

In [ ]:
l = [[1,2,3],[3,4,5],[6,7,8,]]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

array generation function

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,3)   # when u press shift and enter on a particular function it tells us what teh function does
arr

array([1., 3., 5.])

In [ ]:
arr = np.linspace(1,5,5)   # lin space is called linear space and gives equal spaces between each element
arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr = np.linspace(1,5,10)   # lin space is called linear space and gives equal spaces between each element
arr                      # means 1 and 5 k beech mei 10 elements generate karega with equal spaces in between

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

random generation function

In [ ]:
np.random.rand(5)

array([0.13835855, 0.99688891, 0.00644439, 0.70027739, 0.10551773])

In [ ]:
np.random.randn(10)

array([ 1.98809672, -1.2638847 ,  0.38455117,  1.00410626,  2.07904856,
        0.72130942, -1.34795345,  0.54731068, -0.77492885,  0.63183719])

In [2]:
import numpy as np
np.random.randint(6)

4

In [4]:
np.random.randint(10,20,9)

array([10, 12, 10, 18, 17, 10, 18, 13, 11])

array attributes   (attributes are type of variable defined inside a class)

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr.shape

(3, 3)

In [7]:
arr.size

9

In [8]:
arr.dtype

dtype('int64')

array methods


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.min()

np.int64(1)

In [13]:
arr.max()

np.int64(6)

In [14]:
arr.sum()

np.int64(21)