<a href="https://colab.research.google.com/github/Sugandh147/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

basic array creation

In [4]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
import numpy as np
a = [1,2,3,"hello"]
np.array(a)    # datatype u32 means all the datatype have been converted to unicode that is strings cause numpy accepts only similar datatypes

array(['1', '2', '3', 'hello'], dtype='<U21')

In [7]:
import numpy as np
a = [1,2,3,4.6]
np.array(a)    # now everything is converted to float cause ek float value thi so everytging is converted to float (similar datatype)

array([1. , 2. , 3. , 4.6])

In [19]:
l = [[1,2,3],[3,4,5],[6,7,8,]]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])